1st
ice65537/otus-go-hw pull request #5
Opened 2023-01-29 20:28 UTC by ice65537

2023-02-05 22:06 UTC, Nikscorp requested changes
Александр, добрый день.

Задание не принято, есть масса критических замечаний. Пересмотрите пожалуйста полностью лекции связанные с конкурентностью в go.

2023-02-05 22:06 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +var ErrErrorsLimitExceeded error
CRIT: вы используете глобальную переменную для записи. Это критично, если функция Run вызывается конкурентно и ведет к ошибкам.

В исходном примере переменная инициализируются как well-known ошибка к которой предполагается read-only (конкурентно-безопасный) доступ

2023-02-05 22:06 UTC, Nikscorp commented on hw05_parallel_execution/run_test.go
> +		// require.LessOrEqual(t, runTasksCount, int32(2*workersCount+maxErrorsCount), "extra tasks were started")
CRIT: WAT? Нельзя менять исходные тесты если ваша программа не работает

2023-02-05 22:06 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +func getFuncName(i interface{}) string {
CRIT: зачем?

2023-02-13 00:08 UTC, Nikscorp requested changes
Александр, добрый день.

Я не могу принять вашу работу:
1. Вы зачем-то вводите какой-то сомнительный логгинг, используя рефлексию — это загрязняет код и делает его не читаемым.
2. Вы добавляете в ДЗ лишние файлы (main.go).
3. Вы меняете существующие тесты, пытаясь обойти систему проверки.
4. Ваш подход к решению задания хоть и проходит переделанные тесты, но является очень запутанным и неоптимальным — масса дополнительных ресурсов, незакрытых каналов и уникальные подходы к решению — вместо использования стандартных подходов вроде producer-consumer, которые вам давали на лекциях.

Предлагаю переписать ваше решение следующим образом (основываясь на содержании лекций):
1. Валидируете входные значения 
2. Создаете канал для тасок (можно небуферизованный)
3. Запускаете n worker-ов, с wait-группой
4. В воркерах в range цикле читаете канал с тасками обновляя при необходимости счетчик ошибок (с помощью атомика). На каждой итерации проверяете счетчик ошибок — если он больше порогового — return из воркера
5. В основной горутине пишете в канал, проверяя (с помощью атомика счетчик ошибок), если он превысил порог — перестаете писать таски в канал
6. Закрываете канал
7. В основной горутине дожидаетесь завершения всех воркеров и возвращаете результат основанный на счетчике ошибок.

Прошу отнестись ответственнее к выполнению заданий.

2023-02-13 21:01 UTC, ice65537 commented on hw05_parallel_execution/run_test.go
> +		// require.LessOrEqual(t, runTasksCount, int32(2*workersCount+maxErrorsCount), "extra tasks were started")
восстановил исходные тесты

2023-02-13 21:01 UTC, ice65537 commented on hw05_parallel_execution/run.go
> +func getFuncName(i interface{}) string {
интересно было, как понять, что за функция фактически была передана воркеру

2023-02-13 21:34 UTC, ice65537 commented
Уважаемый Никита.
1. Да, это моя вкусовщина. Не противоречит условию задачи. Спецификации вызовов сохранены.
2. Да, я учусь, в т.ч. учился подключать библиотеку из другой папки в exe-шник. Убрал под gitignore.
3. Виноват, сначала поленился, потратил много сил, чтобы мой вариант работал, потом не до конца восстановил тесты. Все вроде вернул обратно как было в изначальных тестах.
4. Я учусь и решение пишу так, чтобы максимально прощупать возможности языка. На этом задании я много помучился и оно работает и проходит уже не переделанные тесты. Я понимаю теперь, что при отсутствии необходимости так делать не следует. Но это и не боевое решение, которое работает в среде с ограниченными ресурсами. Поэтому требовать максимальной эффективности от него не стоит. Я на этом примере научился раз в 20 больше чем на тех, где сходу написал коротенький кусок кода, заодно прощупал те паттерны, которые давали на последующих лекциях. Если где-то остаются незакрытые каналы - прошу ткнуть пальцем.

2023-02-13 21:58 UTC, Nikscorp approved these changes
Окей, так как решение действительно проходит тесты принимаю работу.

Текущая оценка: 7 баллов из 10.
Причины снижения указаны в комментариях к PR.

2023-03-08 13:29 UTC, closed without merging